// @no-cookie-jar
GET http://localhost:9080/ogrod/api/species/
Authorization: Basic YWRtaW46YWRtaW4= #admin:admin
#Authorization: Basic dXNlcjE6dXNlcjE= # user1:user1
#Authorization: Basic dXNlcjI6dXNlcjI= # user2:user2
#Authorization: Basic dXNlcjM6dXNlcjM= # user3:user3
####
// @no-cookie-jar
GET http://localhost:9080/ogrod/api/species/405bdf08-6f7f-12ee-b962-0242ac120011
#Authorization: Basic YWRtaW46YWRtaW4= #admin:admin
Authorization: Basic dXNlcjE6dXNlcjE= # user1:user1
#Authorization: Basic dXNlcjI6dXNlcjI= # user2:user2
#Authorization: Basic dXNlcjM6dXNlcjM= # user3:user3
####
// @no-cookie-jar
PUT http://localhost:9080/ogrod/api/species/405bdf08-6f7f-12ee-b962-0242ac120011
#Authorization: Basic YWRtaW46YWRtaW4= #admin:admin
Authorization: Basic dXNlcjE6dXNlcjE= # user1:user1
#Authorization: Basic dXNlcjI6dXNlcjI= # user2:user2
#Authorization: Basic dXNlcjM6dXNlcjM= # user3:user3
Content-Type: application/json

{
  "name": "RAK",
  "price": 123.0,
  "type": "FLOWER"
}

####
// @no-cookie-jar
PATCH http://localhost:9080/ogrod/api/species/405bdf08-6f7f-12ee-b962-0242ac120011
#Authorization: Basic YWRtaW46YWRtaW4= #admin:admin
Authorization: Basic dXNlcjE6dXNlcjE= # user1:user1
#Authorization: Basic dXNlcjI6dXNlcjI= # user2:user2
#Authorization: Basic dXNlcjM6dXNlcjM= # user3:user3
Content-Type: application/json

{
  "name": "NIuEE",
  "price": 16.0
}
####
// @no-cookie-jar
DELETE http://localhost:9080/ogrod/api/species/405bdf08-6f7f-12ee-b962-0242ac120011
#Authorization: Basic YWRtaW46YWRtaW4= #admin:admin
Authorization: Basic dXNlcjE6dXNlcjE= # user1:user1
#Authorization: Basic dXNlcjI6dXNlcjI= # user2:user2
#Authorization: Basic dXNlcjM6dXNlcjM= # user3:user3


####
// @no-cookie-jar
GET http://localhost:9080/ogrod/api/species/4fe18e8e-6f7f-11ee-b962-0242ac120002/plants/
#Authorization: Basic YWRtaW46YWRtaW4= #admin:admin
Authorization: Basic dXNlcjE6dXNlcjE= # user1:user1
#Authorization: Basic dXNlcjI6dXNlcjI= # user2:user2
#Authorization: Basic dXNlcjM6dXNlcjM= # user3:user3

###
// @no-cookie-jar
GET http://localhost:9080/ogrod/api/plants/
#Authorization: Basic YWRtaW46YWRtaW4= #admin:admin
Authorization: Basic dXNlcjE6dXNlcjE= # user1:user1
#Authorization: Basic dXNlcjI6dXNlcjI= # user2:user2
#Authorization: Basic dXNlcjM6dXNlcjM= # user3:user3

###
// @no-cookie-jar
GET http://localhost:9080/ogrod/api/plants/405bdf55-6f7f-11ee-b962-0242ac120002
#Authorization: Basic YWRtaW46YWRtaW4= #admin:admin
Authorization: Basic dXNlcjE6dXNlcjE= # user1:user1
#Authorization: Basic dXNlcjI6dXNlcjI= # user2:user2
#Authorization: Basic dXNlcjM6dXNlcjM= # user3:user3

###
// @no-cookie-jar
DELETE http://localhost:9080/ogrod/api/plants/405bdf55-6f7f-11ee-b962-0242ac120002
#Authorization: Basic YWRtaW46YWRtaW4= #admin:admin
Authorization: Basic dXNlcjE6dXNlcjE= # user1:user1
#Authorization: Basic dXNlcjI6dXNlcjI= # user2:user2
#Authorization: Basic dXNlcjM6dXNlcjM= # user3:user3

###
// @no-cookie-jar
PUT http://localhost:9080/ogrod/api/species/4fe18e8e-6f7f-11ee-b962-0242ac120002/plants/405bdf55-6f7f-11ee-b962-0242ac120002
#Authorization: Basic YWRtaW46YWRtaW4= #admin:admin
Authorization: Basic dXNlcjE6dXNlcjE= # user1:user1
#Authorization: Basic dXNlcjI6dXNlcjI= # user2:user2
#Authorization: Basic dXNlcjM6dXNlcjM= # user3:user3
Content-Type: application/json

{
    "name": "bbb",
    "height": 0.8,
    "plantingDate": "2001-08-04"
}

###
// @no-cookie-jar
GET http://localhost:9080/ogrod/api/plants/405bdf55-6f7f-11ee-b962-0242ac120002
Authorization: Basic YWRtaW46YWRtaW4= #admin:admin
#Authorization: Basic dXNlcjE6dXNlcjE= # user1:user1
#Authorization: Basic dXNlcjI6dXNlcjI= # user2:user2
#Authorization: Basic dXNlcjM6dXNlcjM= # user3:user3

###
// @no-cookie-jar
PATCH http://localhost:9080/ogrod/api/species/4fe18e8e-6f7f-11ee-b962-0242ac120002/plants/405bdf55-6f7f-11ee-b962-0242ac120002
#Authorization: Basic YWRtaW46YWRtaW4= #admin:admin
Authorization: Basic dXNlcjE6dXNlcjE= # user1:user1
#Authorization: Basic dXNlcjI6dXNlcjI= # user2:user2
#Authorization: Basic dXNlcjM6dXNlcjM= # user3:user3
Content-Type: application/json

{
  "name": "bbb",
  "height": 0.23
}
###
// @no-cookie-jar
GET http://localhost:9080/ogrod/api/gardeners
Authorization: Basic YWRtaW46YWRtaW4= #admin:admin
#Authorization: Basic dXNlcjE6dXNlcjE= # user1:user1
#Authorization: Basic dXNlcjI6dXNlcjI= # user2:user2
#Authorization: Basic dXNlcjM6dXNlcjM= # user3:user3
###
// @no-cookie-jar
GET http://localhost:9080/ogrod/api/gardeners/f6492f9c-8c8b-11ee-b9d1-0242ac120002
Authorization: Basic YWRtaW46YWRtaW4= #admin:admin
#Authorization: Basic dXNlcjE6dXNlcjE= # user1:user1
#Authorization: Basic dXNlcjI6dXNlcjI= # user2:user2
#Authorization: Basic dXNlcjM6dXNlcjM= # user3:user3
###
// @no-cookie-jar
PUT http://localhost:9080/ogrod/api/gardeners/f6492f9c-8c8b-11ee-b9d1-0242ac120002
#Authorization: Basic YWRtaW46YWRtaW4= #admin:admin
#Authorization: Basic dXNlcjE6dXNlcjE= # user1:user1
#Authorization: Basic dXNlcjI6dXNlcjI= # user2:user2
#Authorization: Basic dXNlcjM6dXNlcjM= # user3:user3
#Authorization: Basic dXNlcjU6dXNlcjU= # user5:uesr5
Content-Type: application/json

{
  "name": "NOWY_gosc",
  "age": 67,
  "login": "user5",
  "password": "user5"
}

###
// @no-cookie-jar
GET http://localhost:9080/ogrod/api/gardeners/f6492f9c-8c8b-11ee-b9d1-0242ac120002/image
#Authorization: Basic YWRtaW46YWRtaW4= #admin:admin
#Authorization: Basic dXNlcjE6dXNlcjE= # user1:user1
#Authorization: Basic dXNlcjI6dXNlcjI= # user2:user2
#Authorization: Basic dXNlcjM6dXNlcjM= # user3:user3
#Authorization: Basic dXNlcjQ6dXNlcjQ= # user4:uesr4
Authorization: Basic dXNlcjU6dXNlcjU= # user5:uesr5
###
// @no-cookie-jar
PUT http://localhost:9080/ogrod/api/gardeners/f6492f9c-8c8b-11ee-b9d1-0242ac120002/image
#Authorization: Basic YWRtaW46YWRtaW4= #admin:admin
#Authorization: Basic dXNlcjE6dXNlcjE= # user1:user1
#Authorization: Basic dXNlcjI6dXNlcjI= # user2:user2
#Authorization: Basic dXNlcjM6dXNlcjM= # user3:user3
Authorization: Basic dXNlcjU6dXNlcjU= # user5:uesr5
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="image"; filename="aaa.png'

< aaa.png
--boundary--

###
// @no-cookie-jar
DELETE http://localhost:9080/ogrod/api/gardeners/f6492f9c-8c8b-11ee-b9d1-0242ac120002/image
Authorization: Basic YWRtaW46YWRtaW4= #admin:admin
#Authorization: Basic dXNlcjE6dXNlcjE= # user1:user1
#Authorization: Basic dXNlcjI6dXNlcjI= # user2:user2
#Authorization: Basic dXNlcjM6dXNlcjM= # user3:user3